"""
Django settings for ethertoff project.

Generated by 'django-admin startproject' using Django 2.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'oy9@**&*m*wmw&3um_o!xr@e4jig9u+woz6^szs!a%mye5%qut'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    # 'example_theme', ## Add your theme here if any
    'ethertoff',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'etherpadlite',
    'generator',
    'labels',
    'easy_thumbnails',
    'filer',
    'mptt',
    'my_project',
    'going_hybrid'
    #'south'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'my_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'ethertoff.context_processors.site_name',
                'ethertoff.context_processors.pads',
                'ethertoff.context_processors.local',
            ],
        },
    },
]

WSGI_APPLICATION = 'my_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'

# URL that handles the media served from MEDIA_ROOT. Make sure to use a
# trailing slash.
# Examples: "http://example.com/media/", "http://media.example.com/"
MEDIA_URL = '/media/'

PADS_PER_PAGE = 25

PAD_FORCE_EXTENSION = True

PAD_ALLOWED_EXTENSIONS = ['.md', '.css', '.html']

PAD_DEFAULT_EXTENSION = '.md'

SITE_ID = 1

PAD_NAMESPACE_SEPARATOR = '::'
PAD_NAMESPACE_SEPARATOR_DISPLAY = ' → '
MAX_PAD_SAVE_TRIES = 25

from markdown.extensions.toc import TocExtension
from markdown.extensions.footnotes import FootnoteExtension
# from my_project.markdown_inline_reference import InlineReferenceExtension
# from my_project.voice_extension import VoiceExtension
from mdx_figcaption import FigcaptionExtension
from my_project.markdown_del_extension import DelExtension
from my_project.markdown_underline_extension import UnderlineExtension
# from my_project.markdown_raise_blockquote_classes import RaiseBlockquoteClassesExtension
# from my_project.markdown_raise_figure_classes import RaiseFigureClassesExtension
# from my_project.markdown_footnote_insertion_marker import FootnoteInsertionPointExtension
from generator__filer_thumbnails.markdown_make_filer_image_thumbnails import MakeFilerImageThumbnailsExtension


MARKDOWN_SETTINGS = {
    'extensions': [
        'fenced_code',
        FootnoteExtension(UNIQUE_IDS=True),
        'attr_list',
        'def_list',
        'tables',
        'abbr',
        'md_in_html',
        'meta', 
        'smarty', 
        FigcaptionExtension(),
        TocExtension(baselevel=2), 
        'attr_list',
        DelExtension(), 
        UnderlineExtension(),
    ],
    'extension_configs': {
        'extra': {
            'UNIQUE_IDS': True
        },
        'footnotes': {
            'UNIQUE_IDS': True
        }
    }
}   

MARKDOWN_SETTINGS_GENERATOR = MARKDOWN_SETTINGS
MARKDOWN_SETTINGS_GENERATOR['extensions'].append(MakeFilerImageThumbnailsExtension())

try:
    LOCAL_SETTINGS
except NameError:
    try:
        from .local_settings import *
    except ImportError:
        pass

API_LOCAL_URL = None

TREE_PAD_OPEN_MODE = 'w'

THUMBNAIL_HIGH_RESOLUTION = True

THUMBNAIL_PROCESSORS = (
    'easy_thumbnails.processors.colorspace',
    'easy_thumbnails.processors.autocrop',
    #'easy_thumbnails.processors.scale_and_crop',
    'filer.thumbnail_processors.scale_and_crop_with_subject_location',
    'easy_thumbnails.processors.filters'
)

THUMBNAIL_EXTENSION = 'jpg'


"""
    Filer overwrites naming setting in:
    /home/gijs/venvs/seatforthesea/lib/python3.6/site-packages/filer/utils/filer_easy_thumbnails.py

    and:
    /home/gijs/venvs/seatforthesea/lib/python3.6/site-packages/filer/models/abstract.py

    and:
    /home/gijs/venvs/seatforthesea/lib/python3.6/site-packages/filer/fields/multistorage_file.py
    MultiStorageFieldFile

    Only real way to somehow unwrap and rewrap?

    Seems not really possible to work on this from the outside
"""