# Generated by Django 2.0.6 on 2018-06-21 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('display_slug', models.CharField(blank=True, max_length=256, verbose_name='Name as used in URL (use :: for namespacing)')),
                ('display_name', models.CharField(blank=True, max_length=256, verbose_name='Name as used in Display (use → for namespacing)')),
            ],
            options={
                'ordering': ['display_slug', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PadAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorID', models.CharField(blank=True, max_length=256)),
            ],
            options={
                'verbose_name': 'author',
            },
        ),
        migrations.CreateModel(
            name='PadGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupID', models.CharField(blank=True, max_length=256)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.Group')),
            ],
            options={
                'verbose_name': 'group',
            },
        ),
        migrations.CreateModel(
            name='PadServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('url', models.URLField(max_length=256, verbose_name='URL')),
                ('apikey', models.CharField(max_length=256, verbose_name='API key')),
                ('notes', models.TextField(blank=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'server',
            },
        ),
        migrations.AddField(
            model_name='padgroup',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='etherpadlite.PadServer'),
        ),
        migrations.AddField(
            model_name='padauthor',
            name='group',
            field=models.ManyToManyField(blank=True, null=True, related_name='authors', to='etherpadlite.PadGroup'),
        ),
        migrations.AddField(
            model_name='padauthor',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='etherpadlite.PadServer'),
        ),
        migrations.AddField(
            model_name='padauthor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pad',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='etherpadlite.PadGroup'),
        ),
        migrations.AddField(
            model_name='pad',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='etherpadlite.PadServer'),
        ),
    ]
