# Generated by Django 2.1.1 on 2018-10-31 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etherpadlite', '0002_auto_20180919_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='pad',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pad',
            name='publicpadid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
