# Generated by Django 2.1.1 on 2019-04-12 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etherpadlite', '0003_auto_20181031_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pad',
            name='display_name',
        ),
    ]
