# Generated by Django 2.1.1 on 2019-04-16 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etherpadlite', '0004_remove_pad_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pad',
            name='display_slug',
            field=models.CharField(blank=True, max_length=191, unique=True, verbose_name='Name as used in URL (use :: for namespacing)'),
        ),
    ]
