# Generated by Django 2.2.2 on 2019-10-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etherpadlite', '0005_auto_20190416_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='padauthor',
            name='group',
            field=models.ManyToManyField(blank=True, related_name='authors', to='etherpadlite.PadGroup'),
        ),
    ]
