# Generated by Django 3.2.20 on 2024-01-29 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('etherpadlite', '0006_auto_20191008_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtherportOrganisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField()),
                ('members', models.ManyToManyField(related_name='etherportOrganisations', to=settings.AUTH_USER_MODEL)),
                ('padGroup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='etherportOrganisation', to='etherpadlite.padgroup')),
            ],
        ),
    ]
